services:
  navigation:
    image: ghcr.io/airesearchlab/navigation:humble
    environment:
      - LAUNCH_FILENAME=system.launch.py
      - PARAM_FILENAME=nav2_default.yaml
      - USE_COMPOSITION=False
      - USE_RESPAWN=False
      - USE_NAMESPACE=False
      - NAMESPACE=''
      - USE_SIM_TIME=False
      - AUTOSTART=True
      - LOG_LEVEL=info
      - SLAM=False
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
